name: Bug report
description: File a bug
labels: [bug]
body:
  - type: textarea
    id: expected
    attributes: { label: Expected behavior }
  - type: textarea
    id: actual
    attributes: { label: Actual behavior }
  - type: textarea
    id: steps
    attributes: { label: Steps to reproduce }
  - type: input
    id: version
    attributes: { label: App version or git SHA }