name: Feature request
description: Propose an enhancement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes: { label: Problem or opportunity }
  - type: textarea
    id: proposal
    attributes: { label: Proposed solution }
  - type: textarea
    id: impact
    attributes: { label: Impact / risks }